server {
    listen 80;
    server_name www.score-hymn.com;

    access_log /var/log/nginx/score-hymn.access.log;
    error_log  /var/log/nginx/score-hymn.error.log;

    location /api/ {
        # 프로덕션 백엔드 포트
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        # 프로덕션 프론트엔드 포트
        proxy_pass http://127.0.0.1:8080;

        # 기본 프록시 헤더
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name www.score-hymn.com;

    ssl_certificate     /etc/letsencrypt/live/score-hymn.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/score-hymn.com/privkey.pem;

    access_log /var/log/nginx/score-hymn.access.log;
    error_log  /var/log/nginx/score-hymn.error.log;

    location /api/ {
        # 프로덕션 백엔드 포트
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        # 프로덕션 프론트엔드 포트
        proxy_pass http://127.0.0.1:8080;

        # 기본 프록시 헤더
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
